### ISSUE TITLE
cierre inesperado de puerto (windows)

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#12]
1) El puerto aparece en el listado.
2) Al escoger puerto, se habilita botón 'channels'
3) Al configurar 'channels', a veces aparece el siguiente error:     
>  FatalError. An error ocurred at the communication port. Port is either closed or desconected.

![2017-06-07 1007 captura error 1](https://user-images.githubusercontent.com/14864395/26887638-235bed1e-4b6e-11e7-9950-08db9f581364.PNG)

4) Quedan deshabilitados los botones 'channels' y 'stream' (en rojo)
5) Escojo puerto de nuevo del despegable. Aparece ahora el siguiente error:
> PermissionError(13,'Acceso denegado.',None,5)

![2017-06-07 1008 captura conectado tras error 1](https://user-images.githubusercontent.com/14864395/26887726-69b81bb6-4b6e-11e7-80bb-612cb1ef8e7b.PNG)

6) Desconecto dispositivo.
7) Escojo puerto de nuevo del despegable. Aparece el siguiente error:
> FileNotFoundError(2, 'El sistema no puede encontrar el archivo especificado.',None,2)

![2017-06-07 1009 captura puerto desconectado](https://user-images.githubusercontent.com/14864395/26887791-97f53a22-4b6e-11e7-8d4b-ba057ce88ba2.PNG)

**Comment by jsbarbosa** [comment]
Pruebas no realizadas en la versión actual. A hoy debería estar corregido.
