### ISSUE TITLE
_cffi_backend.pyd considerado virus

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#15]
He descomprimido la carpeta zip descargada de [este enlace](https://sourceforge.net/projects/quantum-temp/files/Quantum-win32-x86-1.0.zip/download), el día 8 de junio de 2017.

El antivirus Norton detecta el archivo `_cffi_backend.pyd` como virus, y procede a eliminarlo tan pronto se descomprime la carpeta. A pesar de esto el programa se ejecuta correctamente. Evaluar para qué sirve este archivo, y eliminarlo de ser posible.

A continuación mensaje que entrega el antivirus tras eliminarlo:

![antivirus borra cffibackend](https://user-images.githubusercontent.com/14864395/26933440-2d007c72-4c2c-11e7-8c82-66b36fa4d7e4.PNG)

y el detalle de la amenaza
![antivirus borra cffibackend 2](https://user-images.githubusercontent.com/14864395/26933925-8d0c82a4-4c2d-11e7-8fa3-fcba85045a84.PNG)

**Comment by jsbarbosa** [comment]
Curioso, si bien siempre al compilar lo genera, ahora lo elimina antes de dar la versión final.
