### ISSUE TITLE
nombre archivo por defecto, no efectivo

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#16]
La ruta del archivo por defecto que da el programa es de la forma "documentos/output_fecha_hora.dat". Sin embargo al hacer 'stream' dice que el archivo ya existe. Al cerrar el programa se verifica y los datos quedan guardados en 'documentos/output.dat' en vez de 'documentos/outputFecha_Hora.dat'

![2017-06-14 843am captura archivo nuevo existe](https://user-images.githubusercontent.com/14864395/27135517-4345ba5e-50de-11e7-8605-9dd879eb6038.PNG)

Error encontrado usando versión de software del 11 de julio.

**Comment by jsbarbosa** [comment]
Este issue corresponde con el issue 14.

Se cierra porque es redundante.
