### ISSUE TITLE
corregir proceso de 'append' en archivo de parámetros

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#17]
Al hacer una reescritura en un archivo existente de datos, el programa anexa (append) los nuevos datos al final, lo cual es correcto.

En el archivo de parámetros, output_params.txt, primero escribe los títulos de todas las sesiones, y luego escribe los registros de los parámetros de todas las sesiones. Esto impide llevar registro de la fecha en la cual se hizo cada configuración de parámetros.

Ejemplo de un archivo obtenido, Output_params.txt:
```
##### PARAMETERS USED #####
Reimagined Quantum experiment began at Wed Jun 14 08:43:41 2017
##### PARAMETERS USED #####
Reimagined Quantum experiment began at Thu Jun  8 09:26:05 2017
09:25:31 	Detector A (Delay): 20 ns
09:25:31 	Detector A (Sleep): 25 ns
09:25:31 	Detector B (Delay): 10 ns
09:25:31 	Detector B (Sleep): 25 ns
09:26:05 	Streaming started.
09:26:15 	Fatal Error. An error ocurred at the communication port.  Port is either closed or disconnected.
08:43:37 	Detector A (Delay): 100 ns
08:43:37 	Detector A (Sleep): 25 ns
08:43:37 	Detector B (Delay): 100 ns
08:43:37 	Detector B (Sleep): 25 ns
08:43:41 	Sampling Time: 50 ms
08:43:41 	Coincidence window: 5 ns
08:43:41 	Streaming started.
08:43:43 	Streaming stoped.
```
Este corresponde a datos tomados el 8 de junio, de 9:25 a 9:26am, y luego datos obtenidos el 14 de junio a las 8:43am.

Se pide corregir el proceso de 'append' en el archivo de parámetros.

**Comment by jsbarbosa** [comment]
Ahora el header se graba al iniciar el programa. Si al finalizar el programa el contenido de `params` es únicamente el header lo borra.
