### ISSUE TITLE
imagen gráfico guardada en blanco

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#18]
Al hacer uso del botón de guardar imagen de los datos graficados, este guarda una imagen con los ejes pero sin ninguna curva en ella.

Ejemplo: esto se ve en la pantalla,
![captura pantalla 2](https://user-images.githubusercontent.com/14864395/27136678-8b4abf22-50e1-11e7-88f9-b5b890fe9040.PNG)

y esta es la imagen guardada con el botón del software:
![image-2](https://user-images.githubusercontent.com/14864395/27136695-94ebb2de-50e1-11e7-8986-8ebb131b3ac0.png)

**Comment by jsbarbosa** [comment]
Problema con axes clear de matplotlib. La solución después de horas fue usar la función que usa el NavigationToolbar de matplotlib realizar un par de modificaciones, hacer una implementación propia de clear y una función include.
