### ISSUE TITLE
revisar orden tabulación en ventanas

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#19]
Al oprimir la tecla 'tab' en el menú 'default properties', este salta en desorden entre las posibles entradas. Ahora está en este orden:

- user email
- delay time
- sleep time
- number of detectors
- sampling time
- file name
- coincidence window time
- include date time to name

que no corresponde al orden de los recuadros
![imagen](https://user-images.githubusercontent.com/14864395/27136954-3aad81ca-50e2-11e7-9c88-89c9ba687300.png)

Revisar el orden de tabulación en todas las ventanas.

**Comment by jsbarbosa** [comment]
Resuelto
