### ISSUE TITLE
alineación medida actual a la derecha

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#20]
Cuando la ventana es muy ancha, la alineación a la derecha de los valores del recuadro 'current' se desfasa por un caracter. Cuando el ancho es menor, la alineación es correcta.

Ejemplo: alineación correcta,
![captura pantalla current_ok](https://user-images.githubusercontent.com/14864395/27137287-24489bda-50e3-11e7-83ae-7e6b942c685b.png)

Alineación incorrecta (ventana un poco más ancha que la anterior),
![captura pantalla current_shifted](https://user-images.githubusercontent.com/14864395/27137292-27fabf4c-50e3-11e7-9a33-39b70b614d87.png)

**Comment by jsbarbosa** [comment]
El problema parece haberse resuelto al agregar un nuevo widget en la ventana. Sin embargo falta hacer pruebas en pantallas de mayor tamaño y con mayor cantidad de labels.

**Comment by jsbarbosa** [comment]
En linux el problema aparece con la modificación. Razón por la cual se pasa el control de eventos `resizeEvent` al `widget` contenedor y no a cada `label`. El `widget` se encarga de llamar a cada `label` de forma individual, y ampliarlo o reducirlo.

Pregunta el tamaño de los `labels` y asigna un mismo valor para todos.
