### ISSUE TITLE
medida current debe ser la más reciente

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#21]
En la pestaña donde se muestra el valor 'current' se está mostrando el penúltimo valor leido; debería mostrar el último.

Lo noté haciendo pruebas de tasa de muestreo largas (segundos). Puede verificar que el valor de 'current' corresponde al penúltimo reportado en la pestaña 'data'.

**Comment by jsbarbosa** [comment]
Resuelto, el tema era que los relojes funcionan de forma asincrónica y para tiempos mayores a 200 ms tomaba el mismo de sampling por lo cual no se evidenciaba el cambio rápidamente.

Ahora si la mitad del tiempo de sampling es mayor a 200 ms se toma la mitad del tiempo.

**Comment by daguzman35** [comment]
Consideremos el caso en el que el tiempo de muestreo sea 2 segundos. Interpreto que en este escenario el sistema con la nueva solución tardará 1 segundo en refrescar el dato. El usuario notará este tiempo de retardo en respuesta. Consideremos también que el tiempo máximo de muestreo es de 1000 segundos; no deberíamos esperar 500 segundos (8min) a refrescar pantalla, siendo que el dato ya lo tenemos diponible en memoria.

Para los escenarios lentos, es decir tiempos mayores a 200ms, sugiero refrescar los datos de pantalla a un valor fijo de 100ms después de la adquisición del dato, y no a la mitad del muestreo. Así, para el ejemplo de muestreo de 2 segundos, el dato estaría en pantalla a los 2,1 segundos, y no a los 3 segundos.

P.D. El gráfico también estaba mostrando el penúltimo dato. Verificar que estos cambios afecten tanto el comportamiento de la pestaña 'current' como los datos graficados.

**Comment by jsbarbosa** [comment]
Listo hice una modificación y el comportamiento actual es:

- Los `timers` de `plot` y `current` que tienen un valor por default de 100 ms y 200 ms correspondientemente, mantendrán ese tiempo incluso para valores de sampleos mayores.
- Al agotarse este tiempo llaman a las funciones correspondientes, que ahora verifican si los datos han cambiado o no, dependiendo de esto cambian sus valores o se quedan como están.
