### ISSUE TITLE
no permite asignar ruta por defecto

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/ReimaginedQuantum#25]
El sistema no permite asignar ruta por defecto ni nombre por defecto para los archivos. El error que aparece es: 
> An Error has ocurred.
> 'Main' object has no attribute 'split_extension'

He intentado tanto escribiendo el nombre como 'dataTest', y como 'dataTest.dat'. Debería funcionar en ambos casos. En versiones anteriores esto funcionaba correctamente.
Adjunto pantallazo del error:
![pant1](https://user-images.githubusercontent.com/14864395/31046201-48101f76-a5ba-11e7-93db-02071e8ec818.PNG)

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.0.01
